# Generated by Django 5.1.4 on 2025-01-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('next_of_kin', models.CharField(max_length=50)),
                ('next_of_kin_number', models.CharField(max_length=50)),
                ('displinary_case', models.CharField(choices=[('basic_training', 'Basic Training'), ('bad_behavior', 'Bad Behavior'), ('rudeness', 'Rudeness'), ('bullying', 'Bullying'), ('cheating', 'Cheating'), ('vandalism', 'Vandalism'), ('truancy', 'Truancy'), ('disrespect_authority', 'Disrespect to Authority'), ('theft', 'Theft'), ('substance_abuse', 'Substance Abuse'), ('inappropriate_social_media', 'Inappropriate Social Media Use'), ('fighting', 'Fighting'), ('gambling', 'Gambling'), ('sexual_misconduct', 'Sexual Misconduct'), ('disruptive_behavior', 'Disruptive Behavior'), ('poor_attendance', 'Poor Attendance'), ('failure_to_follow_rules', 'Failure to Follow Rules'), ('other', 'Other')], default='basic_training', max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
