# Generated by Django 5.1.4 on 2025-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], default='male', max_length=50),
        ),
    ]
