# Generated by Django 5.1.4 on 2025-01-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_participant_displinary_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='displinary_case',
            field=models.CharField(choices=[('basic_training', 'Basic Training'), ('bad_behavior', 'Bad Behavior'), ('rudeness', 'Rudeness'), ('bullying', 'Bullying'), ('cheating', 'Cheating'), ('vandalism', 'Vandalism'), ('truancy', 'Truancy'), ('disrespect_authority', 'Disrespect to Authority'), ('theft', 'Theft'), ('substance_abuse', 'Substance Abuse'), ('inappropriate_social_media', 'Inappropriate Social Media Use'), ('fighting', 'Fighting'), ('gambling', 'Gambling'), ('sexual_misconduct', 'Sexual Misconduct'), ('disruptive_behavior', 'Disruptive Behavior'), ('poor_attendance', 'Poor Attendance'), ('failure_to_follow_rules', 'Failure to Follow Rules'), ('other', 'Other')], max_length=50),
        ),
    ]
